name: Check Ticket Service

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'ticket-service/**/*'
  push:
    branches:
      - develop
    paths:
      - 'ticket-service/**/*'

env:
  ORG: knoldus Inc
  PROJECT_NAME: knoldus-leaderboard
  CODESQAUD_URL: https://www.getcodesquad.com/api/add/reports
  AUTHOR: Kirti (KirtiGhugtyal6)
jobs:
  check_ticketservice:
    env:
      MODULE_NAME: ticket_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Run Horusec
      if: github.event_name == 'push'
      env:
        WORKING_DIR: ticket-service
        AUTHOR: rahul.soni@knoldus.com
        HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "false"
      id: run_horusec
      uses: fike/horusec-action@v0.2.2
      with:
        arguments: -p ./$WORKING_DIR --config-file-path=$WORKING_DIR/horusec-config.json -O $WORKING_DIR/sonarqube.json --return-error=false

    - name: Run test cases and generate reports
      working-directory: ticket-service
      env:
        URL: "jdbc:h2:mem:test;MODE=PostgreSQL;"
        DRIVER: "org.h2.Driver"
        USERNAME: 
        PASSWORD:
      run: |
        sudo timedatectl set-timezone Asia/Kolkata
        sbt cpd
        sbt scapegoat
        sbt scalastyle
        sbt coverage test coverageReport 
        
    - name: Sonar coverage report
      if: github.event_name == 'push'
      working-directory: ticket-service
      run:
        sbt sonarScan 
